# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TVZSUW8VMK4TJxmjNPmAVi2tpWJ41K9
"""

pip install fastapi uvicorn fastai

from fastapi import FastAPI
from fastai.text.all import load_learner
import uvicorn

app = FastAPI()

# Load the trained model
learn = load_learner("model.pkl")

@app.get("/")
def home():
    return {"message": "Sentiment Classification API is running"}

@app.post("/predict")
def predict(text: str):
    pred, pred_idx, probs = learn.predict(text)
    return {"prediction": pred, "probability": probs[pred_idx].item()}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)