# -*- coding: utf-8 -*-
"""model.pkl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J5__bfc8Ni48JUPh0i6iZjWgbzpie6cU
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

# Define the zip file name
zip_file_name = "IMDB Dataset.csv.zip"

# Extract the zip file
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall("/content")

# Check extracted files
os.listdir("/content")

import pandas as pd

csv_file_path = "/content/IMDB Dataset.csv"

# Load CSV into Pandas
df = pd.read_csv(csv_file_path)

# Display the first few rows
df.head()

# Part1： Train the AWD_LSTM Model (ULMFiT with fastai)

import pandas as pd
from sklearn.model_selection import train_test_split
import re

# Load dataset
df = pd.read_csv("IMDB Dataset.csv")

# Clean text function
def clean_text(text):
    text = re.sub(r'<br\s*/?>', ' ', text)  # Remove HTML line breaks
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    return text.lower()

# Apply cleaning
df["review"] = df["review"].apply(clean_text)
df["sentiment"] = df["sentiment"].map({"positive": 1, "negative": 0})

# Split dataset
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df["review"], df["sentiment"], test_size=0.2, random_state=42, stratify=df["sentiment"]
)

# Convert to DataFrame
train_df = pd.DataFrame({"text": train_texts, "label": train_labels})
val_df = pd.DataFrame({"text": val_texts, "label": val_labels})

from fastai.text.all import *

dls = TextDataLoaders.from_df(train_df, text_col="text", label_col="label",
                              valid_df=val_df, seq_len=72, bs=64)

dls.show_batch(max_n=3)

learn = text_classifier_learner(dls, AWD_LSTM, metrics=accuracy)
learn.fine_tune(4)
learn.show_results()

learn.save("model.pkl")