# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kc9hsKw7KavDChcOInageslilE6Q7AVe
"""

fastapi
uvicorn
joblib
scikit-learn
pandas
numpy